apiVersion: v1
data:
  apiToken: ${TOKEN}
  dataIngestToken: ${TOKEN2}
kind: Secret
metadata:
  name: ${GROUP}
  namespace: dynatrace
type: Opaque
---
apiVersion: dynatrace.com/v1beta1
kind: DynaKube
metadata:
  name: ${GROUP}
  namespace: dynatrace
  annotations:
    alpha.operator.dynatrace.com/feature-automatic-kubernetes-api-monitoring: "true"
spec:
  apiUrl: https://$DT-API
  skipCertCheck: false
  networkZone: ${GROUP}
  oneAgent:
    classicFullStack:
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
      env:
        - name: ONEAGENT_ENABLE_VOLUME_STORAGE
          value: "true"
        - name: ONEAGENT_CONTAINER_STORAGE_PATH
          value: /opt
      args:
        - --set-host-group= ${GROUP}
  activeGate:
    capabilities:
      - routing
      - kubernetes-monitoring
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1.5Gi
    group: ${GROUP}
